// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzcaeLgqOBrrVD2QzrqJjVN_QSgDKnPQk',
    appId: '1:879877710666:web:eb3cc41a502fb0e00f17b3',
    messagingSenderId: '879877710666',
    projectId: 'quiz-app-7539',
    authDomain: 'quiz-app-7539.firebaseapp.com',
    databaseURL: 'https://quiz-app-7539-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-7539.appspot.com',
    measurementId: 'G-3HT9GLR1TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_6Q7_XXwXfQmOCLSWzNKHuxB1gSizQzE',
    appId: '1:879877710666:android:1c3ad20cd6f72fb50f17b3',
    messagingSenderId: '879877710666',
    projectId: 'quiz-app-7539',
    databaseURL: 'https://quiz-app-7539-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-7539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoLhVMlpTKbO78gxQPjSQG10p02A31_1o',
    appId: '1:879877710666:ios:82c079d65b8449230f17b3',
    messagingSenderId: '879877710666',
    projectId: 'quiz-app-7539',
    databaseURL: 'https://quiz-app-7539-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-7539.appspot.com',
    iosClientId: '879877710666-8g1bu9sn3eacgfr95bisuvcmqiiid9vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.quiz',
  );
}
